### ISSUE TITLE
CONTRIBUTING.md: discussion section does not exist

### ISSUE THREAD

**Issue by jetsimace** [Heatblur-Simulations/f-4e-manual#304]
The discussion section (reference and link in CONTRIBUTING.md does not exist, so a discussion section should either be created or reference and link should be deleted from CONTRIBUTING.md. I would vote for deletion.
(see https://github.com/Heatblur-Simulations/f-4e-manual/blob/master/CONTRIBUTING.md)
(please bare with me as I'm a newbie and this is my first post here... ;-) )

**Comment by Zabuzard** [comment]
@jetsimace Good spot! Thank you very much. I have enabled GH Discussions.
Not sure if it will be used or not, but its there now, cheers! 👍

**Comment by Zabuzard** [comment]
@jetsimace Good spot! Thank you very much. I have enabled GH Discussions.
Not sure if it will be used or not, but its there now, cheers! 👍
