### ISSUE TITLE
Add reference to Screen Source Switch from DSCG controls

### ISSUE THREAD

**Issue by Simo865** [Heatblur-Simulations/f-4e-manual#306]
Suggest adding the following (or similar) wording to the opening para of dscg_controls.md:
"Note that the Screen Source Switch (used to select the source sensor (Radar/TV) or switch off the DSCG screen) is located on the [pedestal group](../pedestal_group.md)."

I struggled to figure out how to turn the screen on as the switch is so far away!

**Comment by Zabuzard** [comment]
Good point. Will do, thank you! :)
